source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :integrate_targets => true
platform :ios, '9.0'

target 'SampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

end
